spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: CUSTOMER-API
          uri: http://127.0.0.1:7070
          predicates:
            - Path=/customer/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:6062/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:6062/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:6062/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: client1
            client-secret: oINIYuIYeybjm9lihgMqIDqkowJU7LZz
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          keycloak-without-test-scope:
            provider: keycloak
            client-id: client2
            client-secret: ePqdi9ur1acNSXQU8iAJ4R88edQYR28X
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 7060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE